on: [ push, pull_request ]

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.4
  test:
    needs: ruby-versions
    name: >-
      Test (${{ matrix.ruby-version }} / ${{ matrix.os }} / DISABLE_REFINEMENTS: ${{ matrix.DISABLE_REFINEMENTS }})
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ ubuntu-latest, macos-latest ]
        exclude:
          - { os: macos-latest, ruby-version: 2.4 }
          - { os: macos-latest, ruby-version: 2.5 }
        DISABLE_REFINEMENTS: [ 1, 0 ]
    runs-on: ${{ matrix.os }}
    env:
      DISABLE_REFINEMENTS: ${{ matrix.DISABLE_REFINEMENTS }}
    continue-on-error: ${{ matrix.ruby-version == 'head' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run the test suite
        run: |
          bundle exec rake
